#!/usr/bin/env bash

# имя функции для запуска
FUNCTION=
if [ ! -z $1 ]; then
    FUNCTION="$1"
fi

showHelp(){
  echo -e "init - установка и 1 запуск"
  echo -e "win32 - собрать win приложение"
  echo -e ""
}

init(){
npm install
sudo npm install -g electron-packager --save-dev
sudo npm install electron-packager -g
npm start
}

win32(){
electron-packager . winElectroPHP --platform=win32
}

linux(){
electron-packager . winElectroPHP --platform=linux
}


   if [ ! -z $(type -t $FUNCTION | grep function) ]; then
        $1
    else
        showHelp
fi
